language: python
python:
  - "3.6"      # current default Python on Travis CI


# command to install dependencies
install:
  - apt-get install anaconda
  - conda install pytest
# command to run tests
script:
  - pytest
