name: GitHub CI
on: [push]

jobs:
  test:
    name: CI Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
    steps:
    - name: Update Conda environment
      uses: ./
      with:
        args: conda env update -f ./test/requirements.yml
    - name: Show Conda environment info
      uses: ./
      with:
        args: conda info
    - name: Prove that flake8 is installed
      uses: ./
      with:
        args: flake8 --version
    - name: Prove that Pytest is installed
      uses: ./
      with:
        args: pytest ./test
