name: CI Linux
on: [push]

jobs:
  test:
    name: CI Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Include $CONDA in $PATH
      run: echo ::add-path::$CONDA/bin
    - name: Print conda info
      run: conda info -a
    - name: Start conda environment
      run: |
        conda create -q -n test-environment python=3.6 pytest pytest-cov codecov
        source activate test-environment
        pytest
